print("Konversi Suhu Sederhana")
print("Silahkan Pilih Satuan Suhu")
print("1. Celsius")
print("2. Kelvin")
print("3. Reamur")
print("4. fahrenheit")
opsi=input("Masukan Pilihan Anda ")
if opsi==("1"):
    c = int(input("masukan suhu celsiusnya = "))
    f = int(9/5*c+32)
    print("f = ",f)
    r = int(4/5*c)
    print("r = ",r)
    k = int(c+273)
    print("k = ",k)
elif opsi==("2"):
    k = int(input("Masukan Suhu Kelvinnya = "))
    c = int(k-273)
    print("c = ",c)
    r = int(4/5*k+273)
    print("r = ",r)
    f = int(k-273*9/5+32)
    print("f = ",f)
elif opsi==("3"):
    r = int(input("masukan suhu reamurnya = "))
    c = int(5/4*r) 
    print("c = ",c)
    k = int(5/4*r+273 )
    print("k = ",k)
    f= int(r*2.25+32)
    print("f = ",f)
elif opsi==("4"):
    f = int(input("Masukan Suhu fahrenheitnya: "))
    c =int(5/9*f-32)
    print("c = ",c)
    k =int(5/9*f-32+273)
    print("k = ",k)